In [2]:
import pandas as pd

In [3]:
url = "data/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
df = pd.read_csv(url)

In [5]:
df

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,104.16.207.165,443,192.168.10.5,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,104.16.28.216,80,192.168.10.5,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,104.16.28.216,80,192.168.10.5,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,104.17.241.25,443,192.168.10.16,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,104.19.196.102,443,192.168.10.5,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225740,192.168.10.15-72.21.91.29-61374-80-6,72.21.91.29,80,192.168.10.15,61374,6,7/7/2017 5:02,61,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225741,192.168.10.15-72.21.91.29-61378-80-6,72.21.91.29,80,192.168.10.15,61378,6,7/7/2017 5:02,72,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225742,192.168.10.15-72.21.91.29-61375-80-6,72.21.91.29,80,192.168.10.15,61375,6,7/7/2017 5:02,75,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225743,192.168.10.15-8.41.222.187-61323-80-6,8.41.222.187,80,192.168.10.15,61323,6,7/7/2017 5:02,48,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
225744,192.168.10.15-8.43.72.21-61326-80-6,8.43.72.21,80,192.168.10.15,61326,6,7/7/2017 5:02,68,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [6]:
df.head()

,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,Total Backward Packets,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.10.5-104.16.207.165-54865-443-6,104.16.207.165,443,192.168.10.5,54865,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,192.168.10.5-104.16.28.216-55054-80-6,104.16.28.216,80,192.168.10.5,55054,6,7/7/2017 3:30,109,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,192.168.10.5-104.16.28.216-55055-80-6,104.16.28.216,80,192.168.10.5,55055,6,7/7/2017 3:30,52,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,192.168.10.16-104.17.241.25-46236-443-6,104.17.241.25,443,192.168.10.16,46236,6,7/7/2017 3:30,34,1,1,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,192.168.10.5-104.19.196.102-54863-443-6,104.19.196.102,443,192.168.10.5,54863,6,7/7/2017 3:30,3,2,0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [16]:
x = range(df[' Label'].size)
y=

range(0, 225745)

In [35]:
# da.columns

In [10]:
# da["Source Port"]     # error

In [11]:

# da.loc[:, ["Source IP", "Source Port", "Destination IP", "Destination Port", "Protocol", "Label"]]

In [12]:
da.iloc[:, [1,2,3,4,5,84]]          # displaying specific columns by iloc

,Source IP,Source Port,Destination IP,Destination Port,Protocol,Label
0,104.16.207.165,443,192.168.10.5,54865,6,BENIGN
1,104.16.28.216,80,192.168.10.5,55054,6,BENIGN
2,104.16.28.216,80,192.168.10.5,55055,6,BENIGN
3,104.17.241.25,443,192.168.10.16,46236,6,BENIGN
4,104.19.196.102,443,192.168.10.5,54863,6,BENIGN
...,...,...,...,...,...,...
225740,72.21.91.29,80,192.168.10.15,61374,6,BENIGN
225741,72.21.91.29,80,192.168.10.15,61378,6,BENIGN
225742,72.21.91.29,80,192.168.10.15,61375,6,BENIGN
225743,8.41.222.187,80,192.168.10.15,61323,6,BENIGN
225744,8.43.72.21,80,192.168.10.15,61326,6,BENIGN

In [19]:
df.iloc[:, [1,2,3,4,5,84]].values           # five-tuple labelled

array([['104.16.207.165', 443, '192.168.10.5', 54865, 6, 'BENIGN'],
       ['104.16.28.216', 80, '192.168.10.5', 55054, 6, 'BENIGN'],
       ['104.16.28.216', 80, '192.168.10.5', 55055, 6, 'BENIGN'],
       ...,
       ['72.21.91.29', 80, '192.168.10.15', 61375, 6, 'BENIGN'],
       ['8.41.222.187', 80, '192.168.10.15', 61323, 6, 'BENIGN'],
       ['8.43.72.21', 80, '192.168.10.15', 61326, 6, 'BENIGN']],
      dtype=object)

In [18]:
fa = df.iloc[[1,2,3], [1,2,3,4,5,84]]
fa

,Source IP,Source Port,Destination IP,Destination Port,Protocol,Label
1,104.16.28.216,80,192.168.10.5,55054,6,BENIGN
2,104.16.28.216,80,192.168.10.5,55055,6,BENIGN
3,104.17.241.25,443,192.168.10.16,46236,6,BENIGN

In [20]:
# import matplotlib 
# import matplotlib.pyplot as plt
# %matplotlib inline

# import numpy as np

In [20]:

# x =  df.columns.get_loc(Label)
# y =  da['BMXWT']